import React from 'react';
import BannerSection from "../../components/banner/banner";
import '../../assets/style/privacy.css';

const Privacy = () => {
  return (
    <>
    <BannerSection
        pageName="Privacy and Policy"
        name="Privacy and Policy"
      />
    <div style={{ padding: '20px' }} className='container average privacy'>
      <h1 style={{textAlign:'center'}}>Privacy Policy </h1>
      <p style={{paddingTop:'50px',paddingBottom:'20px'}}>Last updated: July 09, 2024 </p>

      <p>
        This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use our Service and informs you about your privacy rights and how the law protects you.
      </p>
      <p>
        We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
      </p>
<br />
      <h4><strong>1. Interpretation and Definitions</strong></h4>
      <h4 style={{paddingTop:'40px'}}><strong>Interpretation</strong></h4>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h4><strong>Definitions</strong></h4>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Dravanti Middle East.</li>
        <li><strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: United Arab Emirates.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Dravanti Group, accessible from www.dravantigroup.com.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h4><strong>2. Collecting and Using Your Personal Data</strong></h4>
      <h4><strong>Types of Data Collected</strong></h4>
      <h4><strong>Personal Data</strong></h4>
      <p>
        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
      </ul>

      <h4><strong>Usage Data</strong></h4>
      <p>
        Usage Data is collected automatically when using the Service.
      </p>
      <p>
        Usage Data may include information such as your Device’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
      </p>

      <h4><strong>Tracking Technologies and Cookies</strong></h4>
      <p>
        We use Cookies and similar tracking technologies to track the activity on our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. The technologies we use may include:
      </p>
      <ul>
        <li><strong>Cookies</strong> or Browser Cookies: A cookie is a small file placed on your Device.</li>
        <li><strong>Web Beacons</strong>: Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs).</li>
      </ul>

      <h4><strong>3. Use of Your Personal Data</strong></h4>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>To manage Your Account: to manage your registration as a user of the Service.</li>
        <li>For the performance of a contract: development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased.</li>
        <li>To contact you: to contact you by email, phone, SMS, or other electronic means.</li>
        <li>To provide you with news, special offers, and general information about other goods and services we offer.</li>
      </ul>

      <h4><strong>4. Retention of Your Personal Data</strong></h4>
      <p>
        The Company will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.
      </p>

      <h4><strong>5. Transfer of Your Personal Data</strong></h4>
      <p>
        Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located.
      </p>

      <h4><strong>6. Delete Your Personal Data</strong></h4>
      <p>
        You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you.
      </p>

      <h4><strong>7. Disclosure of Your Personal Data</strong></h4>
      <p>
        Business Transactions: If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
      </p>
      <p>
        Law Enforcement: Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).
      </p>

      <h4><strong>8. Security of Your Personal Data</strong></h4>
      <p>
        The security of your Personal Data is important to us, but no method of transmission over the Internet or method of electronic storage is 100% secure.
      </p>

      <h4><strong>9. Children’s Privacy</strong></h4>
      <p>
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
      </p>

      <h4><strong>10. Links to Other Websites</strong></h4>
      <p>
        Our Service may contain links to other websites that are not operated by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
      </p>

      <h4><strong>11. Changes to this Privacy Policy</strong></h4>
      <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
      </p>

      <h4><strong>12. Contact Us</strong></h4>
      <p>If you have any questions about this Privacy Policy, you can contact us:</p>
      <ul>
        <li>By email: <a style={{textDecoration:'none',color:'black'}} href="mailto:info@dravantigroup.com">info@dravantigroup.com</a></li>
        <li>By phone: TBC</li>
      </ul>
      <p>By using our Service, you acknowledge that you have read and understood this Privacy Policy and agree to its terms.</p>
    </div>
    </>
  );
}

export default Privacy;
